# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOLPIHi7h4XkFwJUH9dapZd9IVF4RoDa
"""



from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt

filename=list(uploaded.keys())[0]

header=pd.read_csv(io.BytesIO(uploaded[filename]),skiprows=12, nrows=1)
#print(header)
df= pd.read_csv(io.BytesIO(uploaded[filename]), skiprows=13, nrows=1500)
#print(df.iloc[10,6])
# Assuming the 7th column is the 6th index (since indexing starts at 0)
filtered_df = df[df.iloc[:, 6] < 4]



# Extract the data for the histogram (7th column)
data = filtered_df.iloc[:, 6].dropna()  # Drop NaN values for the histogram

# Plot the histogram
plt.figure(1)
plt.hist(data, bins=10)
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.title("Histogram of Filtered Data (10 Bins)")

# Calculate estimated probabilities for each bin
hist, bin_edges = np.histogram(data, bins=10, density=True)


plt.figure(2)
n = len(data)  # Number of data points
cv_scores = []
bin_widths = []

for num_bins in range(1, 1001):
    h = (data.max() - data.min()) / num_bins  # Bin width
    hist, bin_edges = np.histogram(data, bins=num_bins, density=True)
    estimated_probabilities = hist * np.diff(bin_edges)

    cv_score = (2 / ((n - 1) * h)) - (((n + 1) / ((n - 1) * h)) * np.sum(estimated_probabilities**2))

    cv_scores.append(cv_score)
    bin_widths.append(h)

# Plot the cross-validation scores
plt.plot(bin_widths, cv_scores)
plt.xlabel("Bin Width (h)")
plt.ylabel("Cross-Validation Score (Jˆ(h))")
plt.title("Cross-Validation Score vs. Bin Width")

# Save the plot
plt.savefig("crossvalidation.png")

plt.show()

# Find the index of the minimum cross-validation score
optimal_idx = np.argmin(cv_scores)

# Get the optimal bin width
optimal_bin_width = bin_widths[optimal_idx]

# Print the optimal bin width
print(f"The optimal bin width (bandwidth) is: {optimal_bin_width}")

# Calculate the number of bins
data_range = 4
num_bins = int(data_range / optimal_bin_width)

# Plot the histogram with the specified bin width
plt.figure(1)
plt.hist(data, bins=num_bins)  # setting the range explicitly
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.title(f"Histogram with Bin Width {optimal_bin_width}")

# Calculate estimated probabilities for each bin
hist, bin_edges = np.histogram(data, bins=num_bins, range=(data.min(), data.min() + data_range), density=True)

# Show the plot
plt.show()

import pandas as pd
import io
import numpy as np
import matplotlib.pyplot as plt

# Assuming 'data' is already filtered as per your earlier code and contains the 7th column's data.
# You mentioned bin width (0.06836) and range (4).

# Calculate the number of bins
data_range = 4
num_bins = int(data_range / optimal_bin_width)

# Plot the histogram with the specified bin width
plt.figure(1)
plt.hist(data, bins=num_bins, range=(data.min(), data.min() + data_range))  # setting the range explicitly
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.title(f"Histogram with Bin Width {bin_width}")

# Calculate estimated probabilities for each bin
hist, bin_edges = np.histogram(data, bins=num_bins, range=(data.min(), data.min() + data_range), density=True)

# Show the plot
plt.show()